### ISSUE TITLE
Tela de apresentação com a lista de Praças (CEUs) e a instrução (SELECIONE SUA PRAÇA)

### ISSUE THREAD

**Issue by marcoamarelo** [culturagovbr/epracas-backend#2]
Quando clicado, direciona o cadastro pra o ID da Cultura

**Comment by marcoamarelo** [comment]
Quando clicado, direciona o cadastro pra o ID da Cultura

**Comment by nitaibezerra** [comment]
Lista obtida a partir do mapas.cultura.gov.br (API).
