### ISSUE TITLE
Criar o formulário com os campos necessários para o cadastro mínimo (campos que já não estejam contempladas pelo ID Cultura)

### ISSUE THREAD

**Issue by marcoamarelo** [culturagovbr/epracas-backend#4]
O formulário, além de conter as informações básicas do usuário, no ato de cadastro ele também já pode se declarar administrador de uma praça (ou não).

**Comment by nitaibezerra** [comment]
Os campos são contemplados pelo ID da Cultura. Basicamente teremos que incluir a área para subir doc comprobatória de vínculo com a praça: 1) Documento pessoal; 2) Documento comprobatório de vínculo (ex: portaria de nomeação).
